# Generated by Django 4.0.4 on 2022-05-23 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('bedroom', models.IntegerField()),
                ('bath', models.IntegerField()),
                ('square_feet', models.IntegerField()),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
