# Generated by Django 4.0.4 on 2022-05-23 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='sale',
        ),
    ]
